version: '3'

services:

  #PostgreSQL & PGAdmin
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: its
      POSTGRES_PASSWORD: its@DASC@2024
      PGDATA: /data/postgres
    volumes:
       - /data/postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: its@vts.org
      PGADMIN_DEFAULT_PASSWORD: its@DASC@2024
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - /data/pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped


networks:
  postgres:
    driver: bridge
