version: '3.8'

services:
  jupyterhub:
    build: .
    image: my_jupyterhub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      - /data/jupyterhub_data2:/srv/jupyterhub/data
    ports:
      - "8001:8000"
    networks:
      - jupyterhub2
    environment:
      GRANT_SUDO: "yes"
    user: root
# volumes:
#   jupyterhub_data:

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
networks:
  jupyterhub2:
    name: jupyterhub2
