version: '3'

services:

  #Minio
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
      - "443:443"
    volumes:
      - /data/minio:/data
    environment:
      MINIO_ROOT_USER: its
      MINIO_ROOT_PASSWORD: its@DASC@2024
    command: server --console-address ":9001" /data
